//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSS.TrackingCenterProcessor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrackingCenterStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrackingCenterStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSS.TrackingCenterProcessor.Resources.TrackingCenterStatus", typeof(TrackingCenterStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Advisor Submission.
        /// </summary>
        internal static string AwaitingAdvisorSubmission {
            get {
                return ResourceManager.GetString("AwaitingAdvisorSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting BD Approval.
        /// </summary>
        internal static string AwaitingBrokerDealerApproval {
            get {
                return ResourceManager.GetString("AwaitingBrokerDealerApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Created.
        /// </summary>
        internal static string DocumentCreated {
            get {
                return ResourceManager.GetString("DocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Submitted.
        /// </summary>
        internal static string DocumentSubmitted {
            get {
                return ResourceManager.GetString("DocumentSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Received.
        /// </summary>
        internal static string ImageReceived {
            get {
                return ResourceManager.GetString("ImageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string NItemViewPDFStatus_Accepted {
            get {
                return ResourceManager.GetString("NItemViewPDFStatus_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string NItemViewPDFStatus_Completed {
            get {
                return ResourceManager.GetString("NItemViewPDFStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string NItemViewPDFStatus_Submitted {
            get {
                return ResourceManager.GetString("NItemViewPDFStatus_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Signature(s).
        /// </summary>
        internal static string PendingSignatures {
            get {
                return ResourceManager.GetString("PendingSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalled from BD.
        /// </summary>
        internal static string RecalledfromBD {
            get {
                return ResourceManager.GetString("RecalledfromBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected by BD.
        /// </summary>
        internal static string RejecteByBrokerDealer {
            get {
                return ResourceManager.GetString("RejecteByBrokerDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Canceled.
        /// </summary>
        internal static string RequestCanceled {
            get {
                return ResourceManager.GetString("RequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Received.
        /// </summary>
        internal static string RequestReceived {
            get {
                return ResourceManager.GetString("RequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Deliver Email.
        /// </summary>
        internal static string UnableToDeliverEmail {
            get {
                return ResourceManager.GetString("UnableToDeliverEmail", resourceCulture);
            }
        }
    }
}
